### ISSUE TITLE
BSP-dec version asks to update some libraries

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#13]
Is it intended? It's like it requires .NET 6.0.0. While the normal editor doesn't ask it.

**Comment by Duude92** [comment]
[HalfLife.UnifiedSdk.MapDecompiler](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler) is based on .net6 platform. I want to update whole project to use .net6. So, yes, its intended. It is possible to downgrade MapDecompiler project, in that case my version would be detached from original repository, and therefore might contain dependency issues (if so). But anyway I plan to update whole project. For that purposes I separate net-update from dev branch, and bsp-dec from net-update

**Comment by Qwertyus3D** [comment]
Alright

**Comment by Qwertyus3D** [comment]
By the way, it only works with windowsdesktop-runtime-6.0.29-win-x86 installed. Not with x64 version or with .NET SDK.

**Comment by Duude92** [comment]
It was initially made to use x86 arch, and did not worked with x64 systems because of imgui.net wrapper, that requires native library cimgui.dll. I added support of x64 native library, and project could be built in "Any CPU" mode, which will build x64 arch application, but I left x86 architecture to keep compatibility with x86 systems
