### ISSUE TITLE
Automatic updates issue

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#15]
The program shows update messages even if I disable the feature in Settings. Moreover, even if I have latest version from GitHub it still suggests me to update. Even when I had that update downloaded, installed and restarted the program, it still shows that message box...

**Comment by Duude92** [comment]
Thanks. Fixed startup update checker.
About updated app: do you encounter that issue with bsp-dec version or stable dev?
Other branch versions still refers to 'latest' release, which is built over 'development' branch, that is stable net472, so it will notify new version even it has no new releases.

**Comment by Qwertyus3D** [comment]
Yes, the app doesn't see difference between development and decompiler version, so it insists on updating with any newer version. But now it doesn't show messages if update check is disabled.

**Comment by Duude92** [comment]
It is related to DateTime of the build. The basic algorithm is that GitHub Actions, after building app, writes its current time into 'build' file. Next, application, on update checks - it retrieves data from GitHub Releases, finds 'latest' release, and compare app build date with release build date. Since I still didn't rename in-app project name (as original author requires) - I dont use app versioning. Anyway, versioning wouldn't help in this situation alot. I would provide more information into build file to compare current build with releases, it should contain at least release name (stable branch, or others). So it might happen when unstable release has build earlier than stable, for example branch with new feature updated 20 min ago - would show there is new update, if stable 'latest' release is published right now.

**Comment by Duude92** [comment]
Seems like updates works fine for now, so I'm closing an issue.
I plan to close .net472 build, since .net6 works fine.
