### ISSUE TITLE
[FEATURE REQUEST] Converting brushes into .smd or .mdl format

### ISSUE THREAD

**Issue by dizzy1666** [Duude92/hammertime#17]
If it possible to make brush-to-model converter like "Propper" or "Map2Prop" in editor? It will reduce number of wpoly on map.

**Comment by Duude92** [comment]
Basic feature done.
Group of brushes could be exported as .mdl model from editor with command Tool->Create prop

![Image](https://github.com/Duude92/hammertime/assets/11941696/70b63692-12a3-48de-80a7-9769cb2e6e76)

Tool encapsulates textures from selected brushes, and builds simple model without animations.
It ignores null and sky textures (should filter other dev textures), and ignore normals.
The result is 3d model, that could be added to map with "cycler" entity, or others

![Image](https://github.com/Duude92/hammertime/assets/11941696/2ac49d1c-8747-48cf-9602-f84293d80b04)

Currently model could be viewed with Jed's model viewer, but doesn't work with HLAM

**Comment by Duude92** [comment]
![Image](https://github.com/Duude92/hammertime/assets/11941696/dfd79968-bc1c-4f0c-a2a6-155c3b8c2b0b)

Added support to build with "transparent" textures.
For that purpose app looks for entities, and looking for renderamt parameter value

**Comment by Duude92** [comment]
Pushed changes into #1 
Has some issues with displaying model in Hammertime Editor, but in-game model displays right

![Image](https://github.com/Duude92/hammertime/assets/11941696/5c6b1ae9-8bad-4d4f-9ac1-a786807f354b)

![Image](https://github.com/Duude92/hammertime/assets/11941696/c0cfbe13-80ec-4f1d-a06d-a2aaeaf59f20)

Editor display issue might be related to MdlModel.CreateTexuture method, since I've packed texture more compact than Sledge author did
